<?
if (count ( $this->mensajes ) > 0) {
	echo '<div class="success">';
	foreach ( $this->mensajes as $msg ) {
		echo $msg . '<br>';
	}
	echo '</div>';
}
?>



<?php
if (isset ( $this->error )) :
	?>
<div class="error">
		<?=$this->escape ( $this->error );?>
</div>

<?php endif;
?>

<div id="default_header_section">
<h3><?=$this->translate ( 'Create a new comment' );?></h3>
</div>

<?php

//$location = Zend_Registry::get('Nolotiro_location');
//echo $location;

//Zend_Debug::dump($location);

?>

<div id="main">
<div class="span-16">

<form action="<?=$this->escape ( $this->form->getAction () )?>"
	method="<?=$this->escape ( $this->form->getMethod () )?>">

      
		
		<?=$this->form?>
		
	
</form>

</div>

</div>
