<div id="location_header_section">
    <h2><?=$this->translate('About nolotiro.org'); ?></h2><br>
    <b><a  href='/' < <?=$this->translate ( 'back to home page' );?></a></b>
</div>

<div id="main">
<div class="span-18">

<div class="ad_excerpt">
<?=$this->translate('txt_about'); ?>
</div>
</div>


<div class="google_ads">
<!-- google adsense block -->
<script type="text/javascript"><!--
google_ad_client = "pub-7190437604389924";
/* 160x600, creado 9/01/10 */
google_ad_slot = "9535564204";
google_ad_width = 160;
google_ad_height = 600;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<!-- end  of google adsense block -->
</div>


</div> <!-- /main -->