<div id="location_header_section">
    <h2><?=$this->translate('About nolotiro.org'); ?></h2><br>
    <b><a href="/"> &laquo; <?php echo $this->translate ( 'back to home page' );?></a></b>
</div>

<div id="main">
<div class="span-18">

<div class="ad_excerpt">
<?=$this->translate('txt_about'); ?>
</div>
</div>


</div> <!-- /main -->

<div class="google_ads">
    <script type="text/javascript"><!--
    google_ad_client = "pub-5360961269901609";
/* 160x600, creado 29/07/11 */
    google_ad_slot = "2897112415";
    google_ad_width = 160;
    google_ad_height = 600;
//-->
    </script>
    <script type="text/javascript"
    src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
    </script>

</div>