<div id="location_header_section">
    <h2><?=$this->translate('Frequently asked questions'); ?></h2><br>
    <b><a  href='/' > &laquo; <?php echo $this->translate ( 'back to home page' );?></a></b>
</div>


<div id="main">
<div class="span-18">
<?=$this->translate('txt_faqs'); ?>
</div> 


<div class="google_ads">
<!-- google adsense block -->
    <script type="text/javascript"><!--
    google_ad_client = "pub-5360961269901609";
/* 160x600, creado 29/07/11 */
    google_ad_slot = "2897112415";
    google_ad_width = 160;
    google_ad_height = 600;
//-->
    </script>
    <script type="text/javascript"
    src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
    </script>

<!-- end  of google adsense block -->
</div>


</div> <!-- /main -->