<?php

/**
 * index home page view
 */

// Render common HTML header
echo $this->render('partials/html_header.phtml');

// Render the common page headers
echo $this->render('partials/login_box.phtml'); 

?>


   		
   		<? if ( count($this->mensajes) > 0)
   				 {
   				    echo '<div class="success">'; 
   					foreach ($this->mensajes as $msg) {
   						echo $msg.'<br>';
   					}
   					echo '</div>';
   				 }
   		?>
   		
   	</div>



<div class="body_container">

	
	<p>
		blablalbalbalb
	</p> 
</div>

<?= $this->render('partials/html_footer.phtml'); ?>