<?php
/**
 * Log in page
 */
$this->page_title = 'Login - nolotiro.com';
// Render common HTML header
echo $this->render('partials/html_header.phtml');

?>

<div id="default_header_section">
<h3>Login</h3>
(If you are a new user, please <a href="/user/register" title="user register" >register here</a>) 
</div>
<div id="main">
<?php if (isset($this->error)): ?>
	<div class="error">
		<?= $this->escape($this->error); ?>
	</div>
<?php endif; ?>


<div class="span-16">

<form action="<?= $this->escape($this->form->getAction()) ?>"
      method="<?= $this->escape($this->form->getMethod()) ?>">
	<fieldset>
	<legend>Please, insert your user and password</legend>
		
		<?= $this->form->username ?>
		
		<?= $this->form->password ?>
		
		<?= $this->form->submit ?>
	</fieldset>
	</form>

</div>
</div>
<?= $this->render('partials/html_footer.phtml'); ?>