<div id="default_header_section">
<h1><?=$this->translate ( 'Login' );?></h1><br><br>
<?=$this->translate ( '(If you are a new user, please' );?>
&nbsp;<a href="/<?=$this->lang;?>/user/register" title="user register"><?=$this->translate ( 'register here' );?></a>)
</div>

<?php
if (isset ( $this->error )) :
	?>
<div class="error">
		<?=$this->escape ( $this->error );?>
	</div>

<?php endif;
?>

<div id="main">
<div class="span-16">

<form action="<?=$this->escape ( $this->form->getAction () )?>"
	method="<?=$this->escape ( $this->form->getMethod () )?>">
<fieldset><legend><?=$this->translate ( 'Please, insert your email and password' );?></legend>
		
		<?=$this->form->email?>
		<?=$this->form->password?>

                <span id="agree">
            <?=$this->form->rememberme.$this->translate('Remember me');?>
            </span>
		
		<?=$this->form->submit?>
		<br />
		<?=$this->translate ( '<a href=\'/en/user/forgot\'>Forgot</a> your password?' );?>
	</fieldset>
</form>
</div>

</div>



<div class="google_ads">
<script type="text/javascript"><!--
google_ad_client = "pub-7190437604389924";
/* 300x250, creado 9/01/10 */
google_ad_slot = "7269761465";
google_ad_width = 300;
google_ad_height = 250;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</div>
