<?php
//create new ad page
$this->page_title = $this->translate ( 'Create a new ad' ) . ' - nolotiro.com';

$locale = Zend_Registry::get ( "Zend_Locale" );
$this->lang = $locale->getLanguage ();

//render common HTML header
echo $this->render ( 'partials/html_header.phtml' );
?>

<div id="default_header_section">
<h3><?=$this->translate ( 'Create a new ad' );?></h3>
</div>

<?php
if (isset ( $this->error )) :
	?>
<div class="error">
		<?=$this->escape ( $this->error );?>
</div>
<?php endif;
?>

<div id="main">
<div class="span-16">


<fieldset><legend><?=$this->translate ( 'Please, fill this form to publish your ad' );?></legend>


		<?=$this->form?>

	</fieldset>



</div>

<? //render the default footer
echo $this->render ( 'partials/html_footer.phtml' );
?>