<div id="default_header_section">
<h3><?=$this->translate ( 'Create a new ad' ).' - '.$this->woeidName;?></h3>

<b><a  href='/<?=$this->lang?>/location/change'><?=$this->translate ( 'change location' );?></a></b>

</div>

<?php
if (isset ( $this->error )) :
	?>
<div class="error">
		<?=$this->escape ( $this->error );?>
</div>
<?php endif;
?>

<div id="main">
<div class="span-16">


<fieldset><legend><?=$this->translate ( 'Please, fill this form to publish your ad' );?></legend>


		<?=$this->form?>

	</fieldset>



</div>
