<?php
/**
 * index home page view
 */
// Render common HTML header


//TODO merge header and footer on a main template
$locale = Zend_Registry::get ( "Zend_Locale" );
$lang = $locale->getLanguage ();


echo $this->render ( 'partials/html_header.phtml' );

?>

<?=$this->render ( 'location/index.phtml' );?>

<?
if (count ( $this->mensajes ) > 0) {
	echo '<div class="success">';
	foreach ( $this->mensajes as $msg ) {
		echo $msg . '<br>';
	}
	echo '</div>';
}
?>

<div id="main">



<?php
//Zend_Debug::dump($this->ad)


if ($this->ad): ?>


       <?php foreach ($this->ad as $key => $val): ?>
        <div class="ad_excerpt">
           <h4><a href="/<?=$lang ?>/ad/show/id/<?=$this->escape($val['id']) ?>"><?=$this->escape($val['title']) ?></a></h4>
           
           <span class="ad_date">Posted on <?=$this->escape($val['date_created']) ?>
            by user 
            <a href="/<?=$lang ?>/user/profile/id/<?=$this->escape($val['user_owner']) ?>"><?=$this->escape($val['user_owner']) ?></a>
            </span>
           <br>
           <span><?php echo $this->escape($val['body']) ?></span>
        </div>
        <hr>
        <?php endforeach; ?>



<?php else: ?>

    <p>There are no ads to display for this location.</p>

<?php endif;?>



</div>

<?=$this->render ( 'partials/html_footer.phtml' );?>


