<?php
//register page
$this->page_title = $this->translate ( 'View ad' ) . $this->ad['title'].' - nolotiro.com';

$locale = Zend_Registry::get ( "Zend_Locale" );
$this->lang = $locale->getLanguage ();

//render common HTML header
echo $this->render ( 'partials/html_header.phtml' );
?>

<div id="default_header_section">
<h3><?=$this->translate ( 'View ad' ).' - '.$this->ad['title'] ?></h3>
</div>


<?php
if (isset ( $this->error )) :
	?>
<div class="error">
		<?=$this->escape ( $this->error );?>
	</div>

<?php endif;
?>
<div id="main">
<div class="span-16">


<?php 
Zend_Debug::dump($this->ad);

?>

</div>


<? //render the default footer
echo $this->render ( 'partials/html_footer.phtml' );
?>