<?
               if ($this->ad['type'] == 1) {
                    $ad_type_txt = 'give';
                }

                if ($this->ad['type'] == 2) {
                    $ad_type_txt = 'want';
                }

?>

<div id="default_header_section">
<h2>
<a href="/<?=$this->lang ?>/woeid/<?=$this->ad['woeid_code'].'/'.$ad_type_txt?>">
           <?=$this->woeidName.' > '. $this->translate((string)$ad_type_txt) ?></a>
</h2>
<h1><?php echo $this->escape($this->ad['title']); ?></h1>
</div>


<?
if (count ( $this->mensajes ) > 0) {
	echo '<div class="success">';
	foreach ( $this->mensajes as $msg ) {
		echo $msg . '<br>';
	}
	echo '</div>';
}
?>


<div id="main">
<div class="span-15">


<?php
// if you are the ad owner or admin, then show edit link
$auth = Zend_Auth::getInstance ();
 if ( ($this->ad['user_owner'] == $auth->getIdentity()->id)  || ($this->userRole == 1) ): ?>
    <div class="edit_ad">
        <a href="/<?php echo $this->lang ?>/ad/edit/id/<?php echo $this->ad['id'] ?>">
            <img alt="<?php echo $this->translate('Edit this ad') ?>" src="/images/edit_ad.png"/>&nbsp;<?php echo $this->translate('Edit this ad') ?></a></div>
<?php endif;?>

       
        <div class="ad_excerpt_show">
          
           <?php
               if ($this->ad['photo'] !== null){
                      echo '<div class="ad_list_image">
                      <a title="'.$this->translate('Click to enlarge photo').'" href="/images/uploads/ads/original/'.$this->ad['photo'].'" rel="superbox[image]">
                      <img alt="'.$this->slugTitle($this->escape($this->ad['title'])).'" src="/images/uploads/ads/100/'.$this->ad['photo'].'" /></a></div>';
               }
	        ?>

           <?php if ($this->ad['type'] == 1): ?>
           <span class="ad_status <?=$this->ad['status'] ?>"><?=$this->translate($this->ad['status']) ?></span>
           <?php endif;?>

           <span class="ad_date"><?=$this->translate('Posted on '). $this->ad['date_created'] ?>
            <?=$this->translate('by user ') ?> 
            <a href="/<?=$this->lang ?>/ad/listuser/id/<?=$this->ad['user_owner'] ?>"><?=$this->ad['username'] ?></a>
            </span>
            
           <br>
           <p><?php echo $this->escapeEmail( $this->escape($this->ad['body']) ) ?></p>


           <div class="ad_meta_info">
               <?=$this->countReadedAd['counter'] . ' ' .$this->translate('readings') ?>

                <?php if ($this->checkCountAd): ?>
                 <?=', '.$this->escape( $this->checkCountAd == null  ? 0 : $this->checkCountAd ).' '.$this->translate('comments') ?>
                 <?php endif;?>
           </div>


           <?php if ($this->ad['status'] != 'delivered'): ?>
	   <?php echo $this->translate('Interested?') ?>&nbsp;
<a href="/<?php echo $this->lang ?>/message/create/id_user_to/<?=$this->ad['user_owner'].'/subject/'.$this->slugTitle($this->escape($this->ad['title']))
        ?>" rel="nofollow"><?php echo $this->translate('Send a private message to the owner') ?> <img src="/images/email_send.png" alt="send a message"/></a>
           <?php endif;?>


<br /><br />

<div class="sharelinks">

    <p style="text-align:left;margin-bottom:5px;"><?=$this->translate('Share this ad:');?></p>
           

    <div id="google-button">
        <g:plusone size="medium" href="<?php echo "http://nolotiro.org/" . $this->lang . "/ad/" . $this->ad['id'] . '/' . $this->slugTitle($this->escape($this->ad['title'])) ?>"></g:plusone>
    </div>

    <div id="twitter-button">
        <a href="http://twitter.com/share" class="twitter-share-button" data-text="http://nolotiro.org/<?=$this->lang;?>/ad/<?=$this->ad['id'].'/'.$this->slugTitle($this->escape($this->ad['title'])) .'  '.$this->escape($this->ad['title']); ?>" data-count="horizontal" data-via="nolotiro" data-related="alabs_es" data-lang="es">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
    </div>

    <div id="facebook-button">
        <iframe allowtransparency="true" src="http://www.facebook.com/plugins/like.php?href=http://nolotiro.org/<?=$this->lang;?>/ad/<?=$this->ad['id'].'/'.$this->slugTitle($this->escape($this->ad['title']));?>&amp;layout=button_count&amp;show_faces=false&amp;width=110&amp;height=21&amp;action=like&amp;font=arial&amp;colorscheme=light" style="border:none; overflow:hidden; width:110px; height:21px" frameborder="0" scrolling="no"></iframe>
    </div>

</div>


</div>

<? if ($this->ad['comments_enabled'] ): ?>
    <? if ($this->comments ): ?>
<div class="ad_comments">
<h5><?=$this->translate ( 'Comments');?></h5>

       <?php foreach ($this->comments as $key => $val): ?>
        <div class="ad_comment">
           <h4><a href="/<?=$this->lang ?>/ad/<?=$this->escape($val['id']).'/'.$this->escape($val['title']) ?>">
           <?=$this->escape($val['title']) ?></a></h4>
           
           <span class="ad_date"><?=$this->translate('Posted on '). $this->escape($val['date_created']) ?>
            <?=$this->translate('by user ') ?>            
                <a href="/<?=$this->lang ?>/profile/<?=$this->escape($val['username']) ?>"><?=$this->escape($val['username']) ?></a>
            </span>
           <br>
           <span><?php echo $this->escapeEmail( $this->escape($val['body']) ) ?></span>
        </div>
        <?php endforeach; ?>
<?php endif;?>



        <?php if($this->ad['status'] != 'delivered' ): ?>
        <div class="ad_comment_form">
        <?=$this->createcomment?>
        </div>
        <?php endif; ?>


<?php endif;?>

</div>

</div><!--end main -->

<div class="google_ads">
<script type="text/javascript"><!--
google_ad_client = "pub-5360961269901609";
/* 300x250, creado 29/07/11 */
google_ad_slot = "5046916921";
google_ad_width = 300;
google_ad_height = 250;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</div>
