<?php
//register page
$this->page_title = $this->translate ( 'View ad' ) . $this->ad['title'].' - nolotiro.com';

$locale = Zend_Registry::get ( "Zend_Locale" );
$this->lang = $locale->getLanguage ();
$aNamespace = new Zend_Session_Namespace('Nolotiro');
				


//render common HTML header
echo $this->render ( 'partials/html_header.phtml' );
?>

<div id="default_header_section">
<h5>
<a href="/<?=$this->lang ?>/ad/list/woeid/<?=$this->ad['woeid_code'].'/ad_type/'.$this->ad['type']?>">
           <?=$aNamespace->locationName.' > '. $this->translate($this->ad['type']) ?></a>
</h5>
<h3><?=$this->ad['title'] ?>
</h3>
</div>


<?
if (count ( $this->mensajes ) > 0) {
	echo '<div class="success">';
	foreach ( $this->mensajes as $msg ) {
		echo $msg . '<br>';
	}
	echo '</div>';
}
?>


<div id="main">
<div class="span-15">


<?php 
//Zend_Debug::dump($this->ad);

if ($this->ad): ?>


       
        <div class="ad_excerpt_show">
          
           <?php
	   if ($this->ad['photo'] !== null){
		      echo '<div class="ad_list_image">
		      <a href="/images/uploads/ads/original/'.$this->ad['photo'].'" rel="superbox[image]">
		      <img alt="'.$this->ad['title'].'" src="/images/uploads/ads/100/'.$this->ad['photo'].'" /></a></div>';
	   }
	   ?>
           <span class="ad_date"><?=$this->translate('Posted on '). $this->ad['date_created'] ?>
            <?=$this->translate('by user ') ?> 
            
           
            <a href="/<?=$this->lang ?>/user/profile/id/<?=$this->ad['user_owner'] ?>"><?=$this->ad['username'] ?></a>
            </span>
           <br>
           <span><?php echo $this->ad['body'] ?></span>
	   
	   
	   
        </div>
        
       
 
<a href="/<?=$this->lang ?>/message/create/id_user_to/<?=$this->ad['user_owner'] ?>"><?=$this->translate('Send a private message') ?></a>


<?php else: ?>

    <p><h3><?=$this->translate ( 'This ad does not exists.');?></h3></p>

<?php endif;?>

<div class="ad_comments">
<h5>Comments</h5>
<?

//comments
//Zend_Debug::dump($this->comments);
if ($this->comments): ?>


       <?php foreach ($this->comments as $key => $val): ?>
        <div class="ad_comment">
           <h4><a href="/<?=$this->lang ?>/ad/show/id/<?=$this->escape($val['id']).'/'.$this->escape($val['title']) ?>">
           <?=$this->escape($val['title']) ?></a></h4>
           
           <span class="ad_date"><?=$this->translate('Posted on '). $this->escape($val['date_created']) ?>
            <?=$this->translate('by user ') ?> 
            
           
            <a href="/<?=$this->lang ?>/user/profile/id/<?=$this->escape($val['user_owner']) ?>"><?=$this->escape($val['user_owner']) ?></a>
            </span>
           <br>
           <span><?php echo $this->escape($val['body']) ?></span>
        </div>
        
        <?php endforeach; ?>



<?php endif;?>

        <div class="ad_comment_form">
        <?=$this->createcomment?>
        </div>



</div>
</div>

<!-- google adsense block -->
<div class="google_ads">
<script type="text/javascript"><!--
google_ad_client = "pub-7190437604389924";
/* 300x250, creado 9/01/10 */
google_ad_slot = "7269761465";
google_ad_width = 300;
google_ad_height = 250;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</div>
<!-- end of google adsense block -->

<? //render the default footer
echo $this->render ( 'partials/html_footer.phtml' );
?>