<div id="default_header_section">
<h3><?=$this->translate ( 'New private message to user:' );?></h3>
</div>

<?php
if (isset ( $this->error )) :
	?>
<div class="error">
		<?=$this->escape ( $this->error );?>
	</div>

<?php endif;
?>

<div id="main">
<div class="span-16">

<form action="<?=$this->escape ( $this->form->getAction () )?>"
	method="<?=$this->escape ( $this->form->getMethod () )?>">
<fieldset><legend><?=$this->translate ( 'Please, write your message' );?></legend>
      
		
		<?=$this->form?>
		
	</fieldset>
</form>

</div>

</div>