<div id="default_header_section">
<h2><?=$this->translate ( 'New private message to user' ). ' ' . $this->user_to ;?></h2>
</div>

<?php
if (isset ( $this->error )) :
	?>
<div class="error">
		<?=$this->escape ( $this->error );?>
	</div>

<?php endif;
?>

<div id="main">
<div class="span-16">

<form action="<?=$this->escape ( $this->form->getAction () )?>"
	method="<?=$this->escape ( $this->form->getMethod () )?>">
<fieldset><legend><?=$this->translate ( 'Please, write your message' );?></legend>
	
	<?=$this->form?>
		
</fieldset>
</form>

</div>

</div>

<!-- google adsense block -->
<div class="google_ads">
<script type="text/javascript"><!--
google_ad_client = "pub-5360961269901609";
/* 300x250, creado 29/07/11 */
google_ad_slot = "5046916921";
google_ad_width = 300;
google_ad_height = 250;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</div>
<!-- end of google adsense block -->