<?php $this->page_title = $this->translate ( 'User profile' ).'  -  '.$this->user['username'] ;?>

<div id="default_header_section">
<h3><?=$this->translate ( 'User profile' ).'  -  '.$this->user['username'];?></h3>
</div>

<?php
if (isset ( $this->error )) :
?>
<div class="error">
		<?=$this->escape ( $this->error );?>
</div>

<?php endif;?>

<div id="main">
<div class="span-18">

<ul id="tabnav">
        <?=$this->editprofile ?>
	<li ><a   id="<?=(preg_match("/profile/", $_SERVER['REQUEST_URI']))?"tab_active":"lala"?>" href="/<?=$this->lang ?>/profile/<?=$this->user[username] ?>"><?=$this->translate('profile');?></a></li>
	<li ><a  id="<?=(preg_match("/listuser/", $_SERVER['REQUEST_URI']))?"tab_active":"lala"?>" href="/<?=$this->lang ?>/ad/listuser/id/<?=$this->user[id] ?>"><?=$this->translate('ads');?></a></li>
</ul>


    <div class="user_profile">

        <?php var_dump($this->listmessages) ?>
    
<?php if ($this->listmessages): ?>

       <?php foreach ($this->paginator as $key => $val): ?>
        <div class="message_excerpt">


        </div>



        <?php endforeach; ?>

        <?php endif; ?>


    </div>



<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'partials/paginator_ads.phtml'); ?>



</div>



