<?php
echo '<?xml version="1.0" encoding="UTF-8" ?>';

//TODO merge header and footer on a main template
$locale = Zend_Registry::get ( "Zend_Locale" );
$lang = $locale->getLanguage ();



echo $this->render ( 'partials/html_header.phtml' );

?>

<div id="default_header_section">
<h3><?=$this->translate ( 'Choose your' ).' "'.ucwords($this->locationtemp)."\"";?></h3>
</div>

<?php

//$aNamespace = new Zend_Session_Namespace('Nolotiro');
//Zend_Debug::dump($aNamespace->locationTemp);
//echo 'view location = '.var_dump($aNamespace->location).'<br>';
//echo 'view locationtemp = '.$aNamespace->locationTemp;



if (isset ( $this->error )) :
	?>
<div class="error">
		<?=$this->escape ( $this->error );?>
	</div>

<?php endif;
?>

<div id="main">
<div class="span-16">

<form action="<?=$this->escape ( $this->form->getAction () )?>"
	method="<?=$this->escape ( $this->form->getMethod () )?>">
<fieldset><legend></legend>


<?

        //echo $this->form->my_select_field;


        //Zend_Debug::dump($this->form->location);

        echo $this->form;
		//echo $this->locationtemp;


		echo '<pre>';
		Zend_Debug::dump($this->places);
		echo '</pre>';



?>

	</fieldset>
</form>

</div>

</div>

<?=$this->render ( 'partials/html_footer.phtml' );?>