<div id="default_header_section">
<h3><?=$this->translate ( 'Change your location' );?></h3>
</div>


<?php
if (count ( $this->mensajes ) > 0) {
	echo '<div class="success">';
	foreach ( $this->mensajes as $msg ) {
		echo $msg . '<br>';
	}
	echo '</div>';
}
?>


<?php
if (isset ( $this->error )) :
	?>
<div class="error">
		<?=$this->escape ( $this->error );?>
	</div>

<?php endif;
?>

<div id="main">
<div class="span-16">

<form action="<?=$this->escape ( $this->form->getAction () )?>"
	method="<?=$this->escape ( $this->form->getMethod () )?>">
<fieldset><legend><?=$this->translate ( 'Please, write your location' );?></legend>


		<?=$this->form?>

	</fieldset>
</form>

</div>

</div>
