<?php
echo '<?xml version="1.0" encoding="UTF-8" ?>';

//TODO merge header and footer on a main template
$locale = Zend_Registry::get ( "Zend_Locale" );
$lang = $locale->getLanguage ();
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?=isset ( $this->page_title ) ? $this->page_title : 'nolotiro.com'?></title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="copyright" content="daniel remeseiro" />
<meta name="DC.Title"
	content="<?=isset ( $this->page_title ) ? $this->page_title : 'nolotiro.com'?>" />
<meta name="robots" content="index,follow" />

<link rel="shortcut icon" href="<?=$this->baseUrl?>/images/favicon.ico" type="image/x-icon" />
<link rel="stylesheet" href="<?$this->baseUrl?>/css/common.css" type="text/css" />
<link rel="stylesheet" href="<?$this->baseUrl?>/css/blueprint/forms.css" type="text/css" />
<link rel="stylesheet" href="<?$this->baseUrl?>/css/blueprint/screen.css" type="text/css" media="screen, projection" />

<!--[if IE]>
    <link rel="stylesheet" href="/css/blueprint/ie.css" type="text/css" media="screen, projection" />
  	<![endif]-->
<script src="<?$this->baseUrl?>/js/jquery.min.js" type="text/javascript"></script>
<script src="<?$this->baseUrl?>/js/site_lang.js" type="text/javascript"></script>
<script src="<?$this->baseUrl?>/js/jquery.superbox-min.js" type="text/javascript"></script>
<script type="text/javascript">
		$(function(){
			$.superbox.settings = {
				closeTxt: "Close",
				loadTxt: "Loading...",
				nextTxt: "Next",
				prevTxt: "Previous"
			};
			$.superbox();
		});
	</script>

</head>



<body>

<?php

//$aNamespace = new Zend_Session_Namespace('Nolotiro');
//Zend_Debug::dump($aNamespace->locationTemp);
//echo 'view location = '.var_dump($aNamespace->location).'<br>';
//echo 'view locationtemp = '.$aNamespace->locationTemp;



if (isset ( $this->error )) :
	?>
<div class="error">
		<?=$this->escape ( $this->error );?>
	</div>

<?php endif;
?>

<div id="main">
<div class="span-16">

<form action="<?=$this->escape ( $this->form->getAction () )?>"
	method="<?=$this->escape ( $this->form->getMethod () )?>">
<fieldset><legend><?=$this->translate ( 'Please, choose to write your location' );?></legend>
      
		
<?
		
        //echo $this->form->my_select_field;
		
        
        //Zend_Debug::dump($this->form->location);
		
        echo $this->form;
		//echo $this->locationtemp;
		
		
		//echo '<pre>';
		//Zend_Debug::dump($this->places);
		//echo '</pre>';

		
		
?>
		
	</fieldset>
</form>

</div>

</div>
</body>