<div id="default_header_section">
<h3><?=$this->translate ( 'Choose your' ).' "'.ucwords($this->locationtemp)."\"";?></h3>
</div>

<?php

//$aNamespace = new Zend_Session_Namespace('Nolotiro');
//Zend_Debug::dump($aNamespace->locationTemp);
//echo 'view location = '.var_dump($aNamespace->location).'<br>';
//echo 'view locationtemp = '.$aNamespace->locationTemp;



if (isset ( $this->error )) :
	?>
<div class="error">
		<?=$this->escape ( $this->error );?>
	</div>

<?php endif;
?>

<div id="main">
<div class="span-16">

<form action="<?=$this->escape ( $this->form->getAction () )?>"
	method="<?=$this->escape ( $this->form->getMethod () )?>">
<fieldset><legend></legend>


<?
        //echo $this->form->my_select_field;
        //Zend_Debug::dump($this->form->location);

        echo $this->form;
		//echo $this->locationtemp;

		//echo '<pre>';
		//Zend_Debug::dump($this->places);
		//echo '</pre>';

?>

	</fieldset>
</form>

</div>

</div>
<!-- google adsense block -->
<div class="google_ads">
<script type="text/javascript"><!--
google_ad_client = "pub-7190437604389924";
/* 300x250, creado 9/01/10 */
google_ad_slot = "7269761465";
google_ad_width = 300;
google_ad_height = 250;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</div>
<!-- end of google adsense block -->