<?php
//TODO merge header and footer on a main template
$locale = Zend_Registry::get ( "Zend_Locale" );
$lang = $locale->getLanguage ();

?>

<div id="location_header_section">
<h3>
<?php
//get the location stored at session location value 
//(setted by default on bootstrap to Madrid woeid number)
$aNamespace = new Zend_Session_Namespace('Nolotiro');
//$this->translate ($aNamespace->ad_type);
echo $aNamespace->locationName;


?>
</h3>


<span class="give-want">
<a class="<?=(preg_match("/give/", $_SERVER['REQUEST_URI']))?"actual":""?>" href='/<?=$lang?>/ad/list/woeid/<?=$aNamespace->location?>/ad_type/give'><?=$this->translate ( 'give' );?></a>
&nbsp;
<a class="<?=(preg_match("/want/", $_SERVER['REQUEST_URI']))?"actual":""?>" href='/<?=$lang?>/ad/list/woeid/<?=$aNamespace->location?>/ad_type/want'><?=$this->translate ( 'want' );?></a>
</span>


<a rel="superbox[iframe][640x280]" href='/<?=$lang?>/location/change'><?=$this->translate ( 'change location' );?></a>


</div>