<?=$this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?=$this->headTitle()->setPrefix('nolotiro.org') ?>
<? //$this->headLink()->appendStylesheet('/css/main.css') ?>
<link rel="shortcut icon" href="/favicon.ico" />
</head>

<body>



<div >


<?php echo $this->layout('error')->content ?>


</div>


</body>
</html>


