<div id="footer">

    <div id="social-butttons">
		<div id="google-button">
            <g:plusone size="medium"></g:plusone>
        </div>
		<div id="twitter-button">
		    <a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="nolotiro" data-related="alabs_es" data-lang="es">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
		</div>
        <div id="facebook-button">
            <iframe src="http://www.facebook.com/plugins/like.php?app_id=239507952749153&amp;href=http%3A%2F%2Fnolotiro.org%2F&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:21px;" allowTransparency="true"></iframe>
        </div>
	</div>

    <div class="links-right">
        <a href='/<?= $this->lang ?>/page/about'><?= $this->translate('about'); ?></a>
        | <a href='/<?= $this->lang ?>/page/faqs'><?= $this->translate('faqs'); ?></a>
        | <a href='/<?= $this->lang ?>/ad/listall/ad_type/give'><?= $this->translate('all the ads'); ?></a>
        | <?= ($this->lang == 'es') ? "<a href='/en/index/setlang'>english</a>"
            : "<a href= '/es/index/setlang'>español</a>"; ?> |&nbsp;&nbsp;
        <a href="http://alabs.es/" ><img src="/images/alabs.png" alt="aLabs logo"></a>
    </div>

    <br/>

    <div id="info" class="innerWrap clearfix">
        <p>
            <?= $this->translate('nolotiro.org is a website where you can give away things you no longer want or no longer need to pick them up other people who may serve or be of much use.');
            ?>
        </p>
    </div>
    <div class="links-left">
        <a href="/<?= $this->lang ?>/page/tos"><?= $this->translate('terms of use'); ?></a> |
        <a href="/<?= $this->lang ?>/page/privacy"><?= $this->translate('privacy policy'); ?></a> |
        <a href="https://github.com/alabs/nolotiro"><?= $this->translate('developers'); ?></a> |
        <a href='/<?= $this->lang ?>/contact'><?= $this->translate('contact'); ?></a> |
        <a href='http://www.pledgie.com/campaigns/12750'><?= $this->translate('donate'); ?></a>
    </div>
</div>