<div id="footer">

    <div id="social-butttons">
		<div id="google-button">
            <g:plusone size="medium" href="http://nolotiro.org/"></g:plusone>
        </div>
		<div id="twitter-button">
		    <a href="http://twitter.com/share" class="twitter-share-button" data-url="http://nolotiro.org/" data-text="No lo tiro, te lo regalo (sin condiciones)" data-count="horizontal" data-via="nolotiro" data-related="alabs_es" data-lang="es">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
		</div>
        <div id="facebook-button">
            <iframe src="http://www.facebook.com/plugins/like.php?href=http://www.facebook.com/nolotiroteloregalo%2F&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:21px;" allowTransparency="true"></iframe>
        </div>
	</div>

    <div class="links-right">
        <a href='/<?= $this->lang ?>/page/about'><?= $this->translate('about'); ?></a>
        | <a href="http://blog.alabs.es/category/nolotiro-org/">blog</a>
        | <a href='/<?= $this->lang ?>/page/faqs'><?= $this->translate('faqs'); ?></a>
        | <a href='/<?= $this->lang ?>/ad/listall/ad_type/give'><?= $this->translate('all the ads'); ?></a>
        | <a href='/<?= $this->lang ?>/page/translate'><?= $this->translate('help to translate'); ?></a>
        &nbsp;&nbsp;


        <a href="http://alabs.es/" ><img src="/images/alabs.png" alt="aLabs logo"></a>
    </div>

    <br/>

    <div id="info" class="innerWrap clearfix">
        <p>
            <?= $this->translate('nolotiro.org is a website where you can give away things you no longer want or no longer need to pick them up other people who may serve or be of much use.');
            ?>
        </p>
    </div>
    <div class="links-left">
        <a href="/<?= $this->lang ?>/page/tos"><?= $this->translate('terms of use'); ?></a> |
        <a href="/<?= $this->lang ?>/page/privacy"><?= $this->translate('privacy policy'); ?></a> |
        <a href="https://github.com/alabs/nolotiro"><?= $this->translate('developers'); ?></a> |
        <a href='/<?= $this->lang ?>/contact'><?= $this->translate('contact'); ?></a> |
        <a href='http://nolotiro.uservoice.com/forums/30282?lang=<?=$this->lang ?>' target="_blank"><?= $this->translate('suggestions'); ?> </a>
    </div>
</div>