<?php include_once("header_common.phtml"); ?>
<body>
<div class="container">
    <div id="header">

        <div id="select_language_box">
                    <?php
                    $langs = Zend_Registry::get("languages");
                    $activelangs = Zend_Registry::get("activelangs");
                    foreach ($langs as $lang => $name):
                        $langlink = "/$lang/index/setlang";
                        if ($activelangs[$lang] == 1) {
                            $beta = " beta";
                            $beta_lang = "<span class='beta_lang'></span>";
                            if ($this->lang == $lang) $langlink = "/$lang/page/translate?lang=$lang";
                        } else {
                            $beta = $beta_lang = "";
                        }
                        ?>
                        <a class="lang<?=($this->lang == $lang) ? " active" : ""?>" href='<?=$langlink?>'><span
                            class="flag <?=$lang . $beta?>"></span><?=$beta_lang?><span ><img src="/images/flags/<?=$lang?>.gif" alt="<?=$name?>">
                            &nbsp;<?=$name?>
                           </span></a>
                        <?php endforeach;?>
                    <a href='/<?php echo $this->lang?>/page/translate'><?php echo $this->translate('Other');?>...</a>
                </div>


        <div class="user_login_box">
            <?php


            $auth = Zend_Auth::getInstance();
            if (!$auth->hasIdentity()) {

                echo '<a href="/' . $this->lang . '/user/register">' . $this->translate('new user') . '</a> ' .
                    $this->translate('or') . ' ';
                echo '<a href="/' . $this->lang . '/auth/login">' . $this->translate('login') . '</a>';
            } else {

                $auth_username = $auth->getIdentity()->username;
                $auth_userid = $auth->getIdentity()->id;

                echo $this->translate('hello,') . '<b>&nbsp;<a href="/' .
                    $this->lang . '/profile/' . $this->escape($auth_username) . '">' . $this->escape($auth_username) . '</a></b> ';

                //check messages
                // if ( $this->checkMessages > 0) {
                echo '| <a title="' . $this->translate('new messages') . '" href="/' . $this->lang . '/message/received">
                            <img src="/images/icons/ico_email.gif" />&nbsp;<b>' . $this->checkMessages . '</b>
                            </a> ';
                //}
                echo'| ' . '<a href="/' . $this->lang . '/auth/logout">' .
                    $this->translate('logout') . '</a>';
            }
            ?>
        </div>


        <div class="site-name"><a href="/<?php echo $this->lang ?>" title="nolotiro.org home"><img
            src="/images/nolotiro_logo.png" alt="nolotiro.org" id="logo"/> nolotiro.org -</a>
            <?php if ($this->woeid): ?>
                <a href="/<?=$this->lang . '/woeid/' . $this->woeid . '/give'?>"> <?=$this->woeidName  ?></a>
                <?php endif ?>
        </div>

        <div class='site-slogan'><?php echo $this->translate('no lo tiro, te lo regalo (sin condiciones)') ?></div>
        <div class="ad_create_tab">
            <a href="/<?= $this->lang . '/ad/create' ?>"><?= '+ ' . $this->translate('Create new ad') . $this->woeidNameShort;?></a>
        </div>
    </div>

    <?php //if beta lang show info
                       if ($this->advices):
                           foreach ($this->advices as $name => $advice):?>
                           <div id="advice_<?=$name?>" class="advice"><?=$advice?></div>
                           <?php  endforeach; endif;
                       ?>



    <?php echo $this->layout()->content; ?>
    <?php include_once("footer_common.phtml");?>

</div>


</body>
</html>
