<?php
/**
 * Department display page view
 * 
 * @version $Id: show.phtml,v 1.4 2007-12-04 16:54:49 seva Exp $
 */

require_once 'Zend/Controller/Front.php';

// Render common HTML header
echo $this->render('partials/html_header.phtml');

// Render the common page headers
echo $this->render('partials/department_list.phtml');

?>

<div class="body_container">
	<h2>Department View: <?= $this->escape($this->deptname); ?></h2>
<?php if (isset($this->error)): ?>
	<div class="error">
		<?= $this->escape($this->error); ?>
	</div>
<?php else: ?>
	<h3>Employees under <?= $this->escape($this->deptname); ?></h3>
<?php if (! empty($this->employees)): ?>
	<table class="employee_list">
		<tr>
			<th>Name</th>
			<th>Title</th>
			<th>E-mail address</th>
		</tr>
<?php foreach ($this->employees as $emp): ?>
		<tr>
			<td><?= $this->escape($emp->getName()) ?></td>
			<td><?= $this->escape($emp->getTitle()) ?></td>
			<td><a href="mailto:<?= $this->escape($emp->getEmail()) ?>"><?= 
				$this->escape($emp->getEmail()) ?></a></td>
		</tr>
<?php endforeach; ?>
	</table>
<?php else: ?>
	No employees work directly under this department.
<?php endif; ?>

	<h3>Departments under <?= $this->escape($this->deptname); ?></h3>
<?php if (! empty($this->subdepts)): ?>
	<ul class="department_list">
<?php foreach ($this->subdepts as $dep): ?>
		<li><a href="<?= Zend_Controller_Front::getInstance()->getBaseUrl() . 
			'/department/show/name/' . urlencode($dep->getName()) ?>"><?= 
				htmlspecialchars($dep->getName()) ?></a></li>
<?php endforeach; ?>		
	</ul>
<?php else: ?>
	There are no sub-departments under this department. 
<?php endif; ?>	

<?php endif; ?>

</div>

<?= $this->render('partials/html_footer.phtml'); ?>