<?php
/**
 * 500 Error page
 * 
 * @version $Id: 500.phtml,v 1.3 2007-12-04 16:54:49 seva Exp $
 */

header("HTTP/1.x 500 Internal Server Error");

require_once 'Zend/Registry.php';

/* @var $config Zend_Config_Ini */
$config = Zend_Registry::get('config');

?>
<html>

<head>
	<title>Nolotiro.com - 500 Internal Server Error</title>
</head>

<body>
	<h1>Oops...</h1>
	<hr />
	<strong>Nolotiro.com</strong> has encountered some internal error. The application 
	administrators have been informed and this error will be fixed soon (maybe...)
<?php if ($config->debug): ?>
	<div style="overflow: auto; margin-top: 10px; padding: 2px; border: 1px dashed black; background-color: #eee">
		<strong>Debugging information:</strong><br />
		<pre><?= $e->__toString(); ?></pre>
	</div>
<?php endif; ?>
</body>

</html>