<?php $this->page_title = $this->translate ( 'Forgot your password?' ) ; ?>

<div id="default_header_section">
<h3><?=$this->translate ( 'Forgot your password?' );?></h3>
<?=$this->translate ( '(If you are a new user, please' );?>
&nbsp;<a href="/<?=$this->lang;?>/user/register" title="user register"><?=$this->translate ( 'register here' );?></a>)
</div>

<?php
if (isset ( $this->error )) :
	?>
<div class="error">
		<?=$this->escape ( $this->error );?>
	</div>

<?php endif;
?>
<div id="main">
<div class="span-16">


<form action="<?=$this->escape ( $this->form->getAction () )?>"
	method="<?=$this->escape ( $this->form->getMethod () )?>">

<fieldset><legend><?=$this->translate ( 'Please, enter your email address. A new password will be emailed to you' );?></legend>	

<?=$this->form?>

<?=$this->translate ( 'The email address must be the same you used to register.' )?>
</fieldset>
</form>

</div>

