<?php
//register page
$this->page_title = $this->translate('Forgot your password?').' - nolotiro.com';


$locale = Zend_Registry::get("Zend_Locale"); 
$this->lang = $locale->getLanguage();

//render common HTML header
echo $this->render('partials/html_header.phtml');
?>

<div id="default_header_section">
<h3><?=$this->translate('Forgot your password?'); ?></h3>
<?=$this->translate('(If you are a new user, please'); ?>
&nbsp;<a href="/<?=$this->lang; ?>/user/register" title="user register" ><?=$this->translate('register here'); ?></a>) 
</div>

<div id="main">
<div  class="span-16">


<form action="<?=$this->escape($this->form->getAction()) ?>"
      method="<?=$this->escape($this->form->getMethod()) ?>">

<fieldset>
<legend><?=$this->translate('Please, enter your email address and a link will be emailed to you:'); ?></legend>	

<?=$this->form ?>

<?=$this->translate('Byagreemen') ?>
</fieldset>
</form>

</div>


<?//render the default footer
echo $this->render('partials/html_footer.phtml');
?>