<?
$this->page_title = 
    $this->translate ( 'User profile' ) . '  -  ' .  $this->user['username'];
?>

<div id="default_header_section">
  <h2><?=$this->page_title?></h2>
  <?=$this->sendmessage_tab?>
</div>

<?
if (isset ( $this->error )) {
?>

<div class="error">
  <?=$this->escape ( $this->error )?>
</div>

<?
}

if (count ( $this->mensajes ) > 0) {
  echo '<div class="success">';
  foreach ( $this->mensajes as $msg ) {
    echo $msg . '<br>';
  }
  echo '</div>';
}
?>

<div id="main">

  <div class="span-18">

  <?=$this->render('partials/tabnav.phtml')?>

<?
var_dump($this->friendlist);
?>

    <div class="user_profile">
      <h4>
        <?= $this->translate('User name:') . ' ' .
            $this->user['username']?>
      </h4>
      <h4>
        <?= $this->translate('Member since:') . ' ' .
            $this->betterDate($this->user['created'])?>
      </h4>
    </div>

</div>



