<?php

/**
 * Log in page
 * 
 * @version $Id: login.phtml,v 1.2 2007-12-04 12:19:45 seva Exp $
 */

// Render common HTML header
echo $this->render('partials/html_header.phtml');

?>
<div class="login_container">
	<h2>Please Sign In</h2>
	
<?php if (isset($this->error)): ?>
	<div class="error">
		<?= $this->escape($this->error); ?>
	</div>
<?php endif; ?>

	<form method="post">
		<label for="user">User name:</label>
		<input type="text" name="user" id="user" value="<?= 
			isset($this->user) ? $this->escape($this->user) : '' ?>" /><br />
		
		<label for="password">Password:</label>
		<input type="password" name="password" id="password" value="" /><br />
		
		<div class="button_container">
			<input type="submit" value="Sign In" />
		</div>
	</form>
</div>

<?= $this->render('partials/html_footer.phtml'); ?>