<?php
/**
 * Log in page
 */

// Render common HTML header
echo $this->render('partials/html_header.phtml');

?>

<div id="default_header_section">
<h3>Login</h3>
(If you are a new user, please <a href="/user/register" title="user register" >register here</a>) 

</div>

<?php if (isset($this->error)): ?>
	<div class="error">
		<?= $this->escape($this->error); ?>
	</div>
<?php endif; ?>

	<form method="post">
	<fieldset>
		<label for="user">User name:</label>
		<input type="text" name="user" id="user" value="<?= 
			isset($this->user) ? $this->escape($this->user) : '' ?>" /><br />
		
		<label for="password">Password:</label>
		<input type="password" name="password" id="password" value="" /><br />
		
		
			<input type="submit" value="Sign In" />
	</fieldset>
	</form>


<?= $this->render('partials/html_footer.phtml'); ?>