<?php $this->page_title = $this->translate ( 'User profile' ).'  -  '.$this->user['username'] ;?>

<div id="default_header_section">
<h1><?php echo $this->translate ( 'User profile' ).'  -  '.$this->user['username'];?></h1>
<?php echo $this->sendmessage_tab; ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<?php echo $this->friend_link; ?>&nbsp;&nbsp;

</div>

<?php
if (isset ( $this->error )) :
?>
<div class="error">
		<?=$this->escape ( $this->error );?>
</div>
<?php endif;?>


<?
if (count ( $this->mensajes ) > 0) {
	echo '<div class="success">';
	foreach ( $this->mensajes as $msg ) {
		echo $msg . '<br>';
	}
	echo '</div>';
}
?>

<div id="main">
<div class="span-18">
<?php echo  $this->userLockLink; ?>
<ul id="tabnav">
    <?=$this->editprofile_tab; ?>
	<li ><a   id="<?=(preg_match("/profile/", $_SERVER['REQUEST_URI']))?"tab_active":"lala"?>" href="/<?=$this->lang ?>/profile/<?=$this->user['username'] ?>"><?=$this->translate('profile');?></a></li>
	<li ><a  id="<?=(preg_match("/listuser/", $_SERVER['REQUEST_URI']))?"tab_active":"lala"?>" href="/<?=$this->lang ?>/ad/listuser/id/<?=$this->user['id'] ?>"><?=$this->translate('ads');?></a></li>

</ul>


    <div class="user_profile">
        <h4><?=$this->translate('User name:').' '.$this->user['username'];?></h4>
        <h4><?=$this->translate('Member since:').' '.$this->escape(date( $this->translate('l dS \o\f F Y H:i:s'), strtotime($this->user['created'])));?></h4>

     <?php if ($this->friendlist):
            //var_dump($this->friendlist);
            echo '<div><h4>' . $this->translate('Friends list:'). '</h4>';

     ?>


         <?php
       foreach ($this->friendlist as $key => $val):

       echo  '<a href=" '. '/' . $this->lang . '/profile/' .  $val['username'] . ' ">' . $val['username'] . '</a><br>';
               ?>

        <?php endforeach; ?>

        <?php
        echo '</div>';
        endif; ?>

       

    </div>

</div>

</div>
