<?
$this->page_title = $this->translate('User profile') .'  -  '. $this->userName;
?>

<div id="default_header_section">
  <h1><?=$this->page_title?></h1>
</div>

<?
if (isset ( $this->error )) {
?>

<div class="error">
  <?=$this->escape ( $this->error )?>
</div>

<?
}

if (count ( $this->mensajes ) > 0) {
  echo '<div class="success">';
  foreach ( $this->mensajes as $msg ) {
    echo $msg . '<br>';
  }
  echo '</div>';
}
?>

<div id="main">

  <div class="span-18">

<?
echo $this->userLockLink;

if ($this->myUserId == $this->userId) {
    $this->edit_link = '/' . $this->lang . '/user/edit/id/' . $this->userId;
    $this->edit_text = $this->translate('edit profile');
    $this->edit_id   = '';
    $this->mess_link = '/' . $this->lang . '/message/list';
    $this->mess_text =  $this->translate('messages');
    $this->mess_id   = '';
}
$this->prof_link = '/' . $this->lang . '/profile/' . $this->userId;
$this->prof_text = $this->translate('profile');
$this->prof_id   = 'id="tab_active"';
$this->ads_link  = '/' . $this->lang . '/ad/listuser/id/' . $this->userId;
$this->ads_text  = $this->translate('ads');
$this->ads_id    = '';

echo $this->render('partials/tabnav.phtml');
?>

    <div class="ad_excerpt">

      <h4>
        <?= $this->translate('User name:') . ' ' .
            $this->userName?>
      </h4>
      <h4>
        <?= $this->translate('Member since:') . ' ' .
            $this->betterDate($this->created)?>
      </h4>

      <?=$this->sendmessage_tab?><br/>

      <?=$this->friend_link?>

<?
if ($this->friendlist) {
    echo '<div><h4>' . $this->translate('Friends list:'). '</h4>';
    foreach ($this->friendlist as $key => $val) {
        echo  '<a href=" '. '/' . $this->lang . '/profile/' .  $val['username'] . ' ">' . $val['username'] . '</a><br>';
    }
    echo '</div>';
}
?>

    </div>

  </div>

</div>
