<?php $this->page_title = $this->translate ( 'Register' ) ; ?>

<div id="default_header_section">
<h1><?=$this->translate ( 'New user' );?></h1><br><br>
<?=$this->translate ( '(If you already are a registered user, please' );?>&nbsp;
<a href="/<?=$this->lang?>/auth/login" title="user login"><?=$this->translate ( 'login here' );?></a>)
</div>


<?php
if (isset ( $this->error )) :
	?>
<div class="error">
		<?=$this->escape ( $this->error );?>
	</div>

<?php endif;
?>
<div id="main">
<div class="span-16">


<form action="<?=$this->escape ( $this->form->getAction () )?>"
	method="<?=$this->escape ( $this->form->getMethod () )?>">

<fieldset><legend><?=$this->translate ( 'Please, fill this form to be a nolotiro member' );?></legend>	

<?=$this->form?>

<?=$this->translate ( 'By sending this form, you are indicating that you have read, understood, and agree to nolotiro\'s <a href=\'/en/page/user-agreement\'>user agreement</a> and <a href=\'/en/page/privacy\'>privacy policy.</a>' )?>
</fieldset>
</form>

</div>

</div> <!-- /main -->


<div class="google_ads">
<script type="text/javascript"><!--
google_ad_client = "pub-7190437604389924";
/* 300x250, creado 9/01/10 */
google_ad_slot = "7269761465";
google_ad_width = 300;
google_ad_height = 250;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</div>