<?php $this->page_title = $this->translate ( 'Register' ) ; ?>

<div id="default_header_section">
<h3><?=$this->translate ( 'New user' );?></h3><br><br>
<?=$this->translate ( '(If you already are a registered user, please' );?>&nbsp;
<a href="/<?=$this->lang?>/auth/login" title="user login"><?=$this->translate ( 'login here' );?></a>)
</div>


<?php
if (isset ( $this->error )) :
	?>
<div class="error">
		<?=$this->escape ( $this->error );?>
	</div>

<?php endif;
?>
<div id="main">
<div class="span-16">


<form action="<?=$this->escape ( $this->form->getAction () )?>"
	method="<?=$this->escape ( $this->form->getMethod () )?>">

<fieldset><legend><?=$this->translate ( 'Please, fill this form to be a nolotiro member' );?></legend>	

<?=$this->form?>

<?=$this->translate ( 'By sending this form, you are indicating that you have read, understood, and agree to nolotiro\'s <a href=\'/en/page/user-agreement\'>user agreement</a> and <a href=\'/en/page/privacy\'>privacy policy.</a>' )?>
</fieldset>
</form>

</div>
