<?php
//register page
$this->page_title = 'Register - nolotiro.com';
//render common HTML header
echo $this->render('partials/html_header.phtml');
?>

<div id="default_header_section">
<h3>New user</h3>
(If you already are a registered user, please <a href="/auth/login" title="user login" >login here</a>)
</div>

<div id="main">
<div  class="span-16">


<form action="<?= $this->escape($this->form->getAction()) ?>"
      method="<?= $this->escape($this->form->getMethod()) ?>">

<fieldset>
    <legend>Please, fill this form to be a nolotiro's member</legend>
	<p>
	<?= $this->form->username ?>
    </p>
    
    <?= $this->form->email ?>
    <?= $this->form->email2 ?>
    <?= $this->form->captcha ?>
    <?= $this->form->terms ?>

<?= $this->form->submit ?>
</fieldset>
</form>

</div>
<div >
<img alt="demo banner" src="/images/banner_dummy300x250.jpg">
</div>


<?//render the default footer
echo $this->render('partials/html_footer.phtml');
?>