<?php
/**
 * Zets - department list partial view 
 * 
 * @version $Id: department_list.phtml,v 1.3 2007-12-04 16:54:49 seva Exp $
 */

//require_once 'application/models/Nolotiro/Department.php';
require_once 'Zend/Registry.php';
require_once 'Zend/Controller/Front.php';

$user = Zend_Registry::get('session')->username;
//$deptree = Nolotiro_Department::getDepartmentTreeRoot();

?>
	<div class="user_info">
		Hello, <?= $this->escape($user) ?> | 
		<a href="<?= Zend_Controller_Front::getInstance()->getBaseUrl(); 
			?>/user/logout">Log Out</a>
	</div>
	
	<div class="department_tree">
		<h2>Department List</h2>
		
	</div>