
<hr />
<div id="footer"> 
	  	<a href='/about'>about</a> | <a href='/blog'>blog</a> | <a href='http://twitter.com/nolotiro'>twitter</a> | <a href='/contact'>contact</a> |   <a href='http://code.google.com/p/nolotiro/'>developers</a>
	</div>
</div><!-- /end of container -->
	
<script type="text/javascript">var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));</script>
<script type="text/javascript">var pageTracker = _gat._getTracker("UA-141609-7");pageTracker._initData();pageTracker._trackPageview();</script>


</body>
</html>