<?php
//TODO merge header and footer on a main template
$locale = Zend_Registry::get ( "Zend_Locale" );
$lang = $locale->getLanguage ();

//echo Zend_Version::VERSION;
?>



<div id="footer">

    <div class="links-right">
    <a href='/<?=$this->baseUrl . $lang?>/page/about'><?=$this->translate ( 'about' );?></a>
    | <a href='/<?=$this->baseUrl . $lang?>/page/faqs'><?=$this->translate ( 'faqs' );?></a>
     | <a href='/blog'>blog</a> | <a href='http://twitter.com/nolotiro'>twitter</a>
    | <a href='http://www.facebook.com/group.php?gid=38263634418'><?=$this->translate ( 'facebook group' );?></a>
    </div>



  <div id="info" class="innerWrap clearfix">
    
        <p>
            <?=$this->translate ( 'nolotiro.org is a website where you can give away things you no longer want or no longer need to pick them up other people who may serve or be of much use.' );?>
        	
        </p>  
      
    </div>
   

     
  <div  class="links-left">
    
    <a href="/<?=$this->baseUrl . $lang?>/page/terms"><?=$this->translate ( 'terms of use' );?></a> |
    <a href="/<?=$this->baseUrl . $lang?>/page/privacy"><?=$this->translate ( 'privacy policy' );?></a> |
    <a href='http://code.google.com/p/nolotiro/'><?=$this->translate ( 'developers' );?></a> |
    <a href='/<?=$this->baseUrl . $lang?>/contact'><?=$this->translate ( 'contact' );?></a>
  </div>




</div>
<!-- /end of footer -->

</div>
<!-- /end of container -->






<script type="text/javascript">var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));</script>
<script type="text/javascript">var pageTracker = _gat._getTracker("UA-141609-7");pageTracker._initData();pageTracker._trackPageview();</script>


</body>
</html>