<?php
header('Deity: Flying Spaghetti Monster');
echo '<?xml version="1.0" encoding="UTF-8" ?>';
/**
 * Nolotiro common page header view
 */
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?=isset ( $this->page_title ) ? $this->page_title : 'nolotiro.org'?></title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="copyright" content="daniel remeseiro" />
<meta name="DC.Title"
	content="<?=isset ( $this->page_title ) ? $this->page_title : 'nolotiro.org'?>" />
<meta name="robots" content="index,follow" />

<link rel="shortcut icon" href="<?=$this->baseUrl?>/images/favicon.ico" type="image/x-icon" />
<link rel="stylesheet" href="<?$this->baseUrl?>/css/common.css" type="text/css" />
<link rel="stylesheet" href="<?$this->baseUrl?>/css/blueprint/forms.css" type="text/css" />
<link rel="stylesheet" href="<?$this->baseUrl?>/css/blueprint/screen.css" type="text/css" media="screen, projection" />

<!--[if IE]>
    <link rel="stylesheet" href="/css/blueprint/ie.css" type="text/css" media="screen, projection" />
  	<![endif]-->
<script src="<?$this->baseUrl?>/js/jquery.min.js" type="text/javascript"></script>
<script src="<?$this->baseUrl?>/js/site_lang.js" type="text/javascript"></script>
<script src="<?$this->baseUrl?>/js/jquery.superbox-min.js" type="text/javascript"></script>
<script type="text/javascript">
		$(function(){
			$.superbox.settings = {
				closeTxt: "<?=$this->translate ( 'Cancel' )?>",
				loadTxt: "<?=$this->translate ( 'Loading' )?>...",
				nextTxt: "<?=$this->translate ( 'Next' )?>",
				prevTxt: "<?=$this->translate ( 'Previous' )?>"
			};
			$.superbox();
		});
	</script>

</head>



<body>
<div class="container">

<div id="header">
<?php
$locale = Zend_Registry::get ( "Zend_Locale" );
$this->lang = $locale->getLanguage ();
?>


<div class="user_login_box">
<?php

$auth = Zend_Auth::getInstance ();

if (! $auth->hasIdentity ()) {

	echo '<a href="/' . $this->baseUrl . $this->lang . '/user/register">' . $this->translate ( 'new user' ) . '</a> ' . $this->translate ( 'or' ) . ' ';
	echo '<a href="/' . $this->baseUrl . $this->lang . '/auth/login">' . $this->translate ( 'login' ) . '</a>';
} else {
	$auth_username = $auth->getIdentity ()->username;

	echo $this->translate ( 'hello,' ) . '<b>&nbsp;<a href="/' . $this->lang . '/user/profile/' . $this->escape ( $auth_username ) . '">' . $this->escape ( $auth_username ) . '</a></b> | ' . '<a href="/' . $this->lang . '/auth/logout">' . $this->translate ( 'logout' ) . '</a>';
}

?>



<span class="select_language_box">
<select	name="site_language_code_select" id="site_language_code_select">
	<option <?=$this->lang == 'en' ? 'selected="selected"' : '';?>
		value="<?=$this->baseUrl . 'en'?>" id="en">English</option>
	<option <?=$this->lang == 'es' ? 'selected="selected"' : '';?>
		value="<?=$this->baseUrl . 'es'?>" id="es">Español</option>
</select>
</span>
</div>


<h1 id="site-name"><a href="/<?=$this->lang?>"
	title="nolotiro.org home"> <img
	src="/images/nolotiro_logo.png"
	alt="Nolotiro.org logo" id="logo" />nolotiro.org</a></h1>
<h2 id='site-slogan'><?=$this->translate ( 'no lo tiro, te lo doy (sin condiciones)' )?></h2>

<div class="ad_create_tab">
<a  href="/<?=$this->lang.'/ad/create' ?>"><?='+ '.$this->translate ('Create new ad')?></a></span>
</div>

</div>
