<?php
echo '<?xml version="1.0" encoding="UTF-8" ?>';
/**
 * Nolotiro common page header view
 */
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
  <head>
    <title><?= isset($this->page_title) ? $this->page_title : 'nolotiro.com' ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="copyright" content="daniel remeseiro" />
	<meta name="DC.Title" content="<?= isset($this->page_title) ? $this->page_title : 'nolotiro.com' ?>" />
	<meta name="robots" content="index,follow" />

	<link rel="shortcut icon" href="<?=$this->baseUrl ?>/images/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="<?=$this->baseUrl ?>/css/common.css" type="text/css" />
	<link rel="stylesheet" href="<?=$this->baseUrl ?>/css/blueprint/forms.css" type="text/css" />
	<link rel="stylesheet" href="<?=$this->baseUrl ?>/css/blueprint/screen.css" type="text/css" media="screen, projection" />
  	<link rel="stylesheet" href="<?=$this->baseUrl ?>/css/blueprint/print.css" type="text/css" media="print" /> 
  	<!--[if IE]>
    <link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="screen, projection" />
  	<![endif]-->
    
  </head>


		
<body>
<div class="container">

<div id="header">
    	
<div class="select_language_box">
<select name="site_language_code_select" id="site_language_code_select">
<option value="en" id="en">English</option>
<option value="es" id="es">Español</option>
<option selected="selected" value="es" id="es">Español</option>
</select>
</div>

	<div class="user_login_box">
<?php
/**
 * Nolotiro - login box partial view 
 * 
 */
//$user = Zend_Registry::get('session')->username;
echo 'language= '.$_COOKIE["lang"].'<br>';
if (!$this->user) {
	echo'<a href="'.$this->baseUrl.'user/register">'.$this->translate('new user').'</a> '.$this->translate('or').' ';
	echo'<a href="'.$this->baseUrl.'auth/login">'.$this->translate('login').'</a>';
}else {
	echo 'hello, <b><a href="'.$this->baseUrl.'/user/profile/'.$this->escape($this->user->username).'">'.$this->escape($this->user->username).'</a></b> | '.'<a href="'.$this->baseUrl.'/auth/logout">logout</a>';
}

?>
	</div>
    	
    	
    	
    	<h1 id="site-name"><a href="<?=$this->baseUrl.'/'; ?>" title="nolotiro.com home">      
              <img src="<?=$this->baseUrl; ?>/images/nolotiro_logo.png" alt="Nolotiro.com logo" id="logo" />nolotiro.com</a>
    	    </h1>
    	<h2 id='site-slogan'>&nbsp;no lo tiro, te lo doy (sin condiciones)</h2>
    	
    	
		
    </div>
    
<div id="publi_header">
<img alt="demo banner" src="/images/banner_dummy.gif">
</div>

