<?php
/**
 * Nolotiro - login box partial view 
 * 
 */


$user = Zend_Registry::get('session')->username;
?>
<div class="user_info">

<?php

if (!Zend_Registry::get('session')->logged_in) {
	echo'<a href="'.Zend_Controller_Front::getInstance()->getBaseUrl().'/user/register">new user</a> or ';
	echo'<a href="'.Zend_Controller_Front::getInstance()->getBaseUrl().'/user/login">login</a>';
}else {
	echo 'hello, '.$this->escape($user).' | '.'<a href="'.Zend_Controller_Front::getInstance()->getBaseUrl().'/user/logout">Logout</a>';
}



?>
</div>
	