<?php


if ($this->pageCount > 1): ?>
<div class="pagination">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo '/es/search/?q='.$this->escape($_GET['q']).'&page=' .$this->previous; ?>">
    &lt; <?=$this->translate('Previous'); ?>
  </a> |
<?php else: ?>
  <span class="disabled">&lt; <?=$this->translate('Previous'); ?></span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo '/es/search/?q='.$this->escape($_GET['q']).'&page=' .$page; ?>">
        <?php echo $page; ?>
    </a> |
  <?php else: ?>
    <?php echo $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo '/es/search/?q='.$this->escape($_GET['q']).'&page=' .$this->next; ?>">
    <?=$this->translate('Next'); ?> &gt;
  </a>
<?php else: ?>
  <span class="disabled"><?=$this->translate('Next'); ?> &gt;</span>
<?php endif; ?>
</div>
<?php endif; ?>

