<?php
/**
 * contact  page
 */
$this->page_title = $this->translate ( 'Contact form' ) . ' - nolotiro.com';
?>

<div id="default_header_section">
<h3><?=$this->translate ( 'Contact form' );?></h3>
</div>

<?php
if (isset ( $this->error )) :
	?>
<div class="error">
		<?=$this->escape ( $this->error );?>
	</div>

<?php endif;
?>

<div id="main">
<div class="span-16">

<form action="<?=$this->escape ( $this->form->getAction () )?>"
	method="<?=$this->escape ( $this->form->getMethod () )?>">
<fieldset><legend><?=$this->translate ( 'Please, write your message' );?></legend>
      
		
		<?=$this->form?>
		
	</fieldset>
</form>

</div>

</div>